'''
Created on Oct 7, 2013

@author: kyleg
'''

#HARD SET A WORKSPACE ENVIRONMENT
ws = r'\\gisdata\arcgis\GISdata\KDOT\BTP\Projects\CCL'

#SET THE GEODATABASE CONNECTON FOR CCL PROCESSING
connection0 = r'Database Connections/SQL61_GEOADMIN_CCL.sde'

#SCHEMA.Owner.
schema = "CCL.DBO."

#SET THE GEODATABASE SCHEMA/DBO FOR CCL PROCESSING
connection1 =  connection0+'/'+schema

#SET THE GIS POLYGON LAYER FOR CITY LIMIT COMPARISON
citylimits = r'Database Connections\SDEDEV_GIS_DEV.sde\GIS_DEV.Administrative_Boundary\GIS_DEV.CITY_LIMITS'

#SET THE GIS STATE SYSTEM COUNTY LRS ROUTE LAYER FOR LINEAR REFERENCE
cntyroutelyr = r'Database Connections\SDEDEV_GIS_DEV.sde\GIS_DEV.KDOT_ROADWAY\GIS_DEV.CMLRS'

#SET THE GIS STATE SYSTEM STATE LRS ROUTE LAYER FOR LINEAR REFERENCE
stateroutelyr = r'Database Connections\SDEDEV_GIS_DEV.sde\GIS_DEV.KDOT_ROADWAY\GIS_DEV.SMLRS'

#SET THE LOCATION OF THE "LANE CLASS" POLYLINE FEATURE CLASS EXTRACTED FROM CANSYS
laneclass = r"\\gisdata\arcgis\GISdata\KDOT\BTP\CANSYSTEST\CANSYSNet2013_10_7.gdb\LNCL"

#SET THE LOCATION OF THE "INTERCHANGE" POINT FEATURE CLASS EXTRACTED FROM CANSYS
interchange = r"\\gisdata\arcgis\GISdata\KDOT\BTP\CANSYSTEST\CANSYSNet2013_10_7.gdb\INTR"

#NON STATE SYSTEM GIS LAYER
nonstate = "Database Connections\GISPROD.sde\SHARED.NON_STATE_SYSTEM"

